### ISSUE TITLE
新手 我运行了docker命令 没有展示

### ISSUE THREAD

**Issue by starql** [chow-q/CutImage#1]
你好 我是一个docker新手 我运行了你提供的命令 但是什么都没发生 请问如何具体使用?

**Comment by chow-q** [comment]
然后你就可以用浏览器去访问：ip:8000

或者你可以访问我的试用网站：https://huggingface.co/spaces/chow-q/cut-image

**Comment by starql** [comment]
我已经成功访问了,我看了img.py 我想把它作为一个服务功能可以批量扣图,正在尝试 大佬可以加个好友不

**Comment by chow-q** [comment]
有需要可以把联系方式发我邮箱：313733727@qq.com
